version: '3'
services:
  proxy:
    container_name: proxy
    build: proxy
    restart: always
    depends_on:
      - backend
    ports:
      - 80:80
    volumes:
      - ./web/conf.d:/etc/nginx/conf.d
    networks:
      - frontnet
  backend:
    build: backend
    restart: always
    container_name: "backend"
    expose:
      - 8000
    networks:
      - backnet
      - frontnet
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
networks:
  backnet:
  frontnet:

