version: '3'
services:
  backend:
    build: backend
    restart: always
    container_name: "backend"
    expose:
      - 8000
    networks:
      - backnet
      - frontnet
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
networks:
  backnet:
  frontnet:

